services:
  mongodb-limpa-max:
    image: prismagraphql/mongo-single-replica:5.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: joao
      MONGO_INITDB_ROOT_PASSWORD: carlos
      MONGO_INITDB_DATABASE: mydb
    ports:
      - 27017:27017
    volumes:
      - mongodb-limpa-max:/mongodb

volumes:
  mongodb-limpa-max:
